# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: install apt packages
          command: |
            sudo apt-get install -y cmake
      - run:
          name: install pip
          command: |
            sudo pip install 'pip==18.0'
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      # run tests!
      - run:
          name: run flake8
          command:
            pienv run flake8
      - run:
          name: run mypy
          command:
            pipenv run mypy --ignore-missing ./
      - run:
          name: run tests
          command: |
            pipenv run python -m pytest -vv
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports
          destination: tr1
